# Build settings
markdown: kramdown
#highlighter: pygments
highlighter: rouge
gems:
  - jemoji

# Site settings
title: "Mean Jean Oaks"
description: > # this means to ignore newlines until "email:"
   Brooklyn, New York.

email: meanjeanoaks@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'The Mean Jean Oaks'
author: 'The Mean Jean Oaks'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://themeanjeanoaks.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/TheMeanJeanOaks
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    target: '_blank'

  - icon:	facebook
    url:	https://www.facebook.com/pages/Mean-Jean-Oaks/430790827017654
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: instagram
    url:  https://www.instagram.com/meanjeanoaks
    desc: Instagram
    share_url:
    share_title:
    share_link:

  - icon:  spotify
    url: https://open.spotify.com/artist/7fdNgYNzy6a4HcBTgtxNH5
    desc:  Spotify
    share_url:
    share_title:
    share_link:
    target: '_blank'

  - icon:  music
    url: https://meanjeanoaks.bandcamp.com
    desc:  bandcamp
    share_url:
    share_title:
    share_link:
    target: '_blank'
    
#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
